// <auto-generated />
namespace MyPodWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class getSubscriptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(getSubscriptions));
        
        string IMigrationMetadata.Id
        {
            get { return "201701082044331_getSubscriptions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
